artifacts_root: artifacts      # Root directory for all artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Kkalkotwar/data_repository/raw/refs/heads/main/winequality-data.zip   # URL to download the dataset from my GitHub repository
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt